### ISSUE TITLE
No events propagate properly to LUISlider, LUICheckbox, etc.

### ISSUE THREAD

**Issue by tzaeru** [tobspr/LUI#3]
Most widgets in Elements.py seem to have broken amist recent changes to Panda3D; No events arrive to them.

main.py in /Builtin can be ran to quickly notice this.

I tried to tweak LUISlider back to work, but I just can't figure what I'm doing wrong with it -- LUIButton, LUISpriteButton, LUILabel, still work OK.

**Comment by tobspr** [comment]
This is because the controls have not been reworked yet, so they do not work with the new event system. 
With the new system, only solid elements recieve and trigger events. You can make an element solid by specifying it in the constructor (the solid parameter). 
The controls with demos have been reworked yet, I did not have time to rework the other controls yet :) It takes some time because I also clean up and comment the source code when I rework a control.
Am 04.03.2015 16:33 schrieb tzaeru notifications@github.com:Most widgets in Elements.py seem to have broken amist recent changes to Panda3D; No events arrive to them.

main.py in /Builtin can be ran to quickly notice this.

I tried to tweak LUISlider back to work, but I just can't figure what I'm doing wrong with it -- LUIButton, LUISpriteButton, LUILabel, still work OK.

**Comment by tzaeru** [comment]
Oh, it's the solid part. =D

Thanks. I was trying -everything- to fix a few widgets! Got Slider to work now, I'll prolly push some changes on the weekend..

In other news -- I did somekinda hierarchical tree-list widget. The basics work ok, still need to add automatic sorting and somekinda feature to automatically show an optional cross / minus sign when a branch is open/closed. The underlaying LUI parent-child and layout thingy are pretty great and made it an easy widget to add.
